name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Android target
      run: rustup target add aarch64-linux-android

    - name: Download and install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27.0.12077973-linux.zip -O ndk.zip
        unzip ndk.zip
        mv android-ndk-r27.0.12077973 $HOME/ndk
      # NDK路径为 $HOME/ndk

    - name: Install cargo-ndk
      run: cargo install cargo-ndk

    - name: Configure .cargo/config.toml
      run: |
        mkdir -p .cargo
        echo '[target.aarch64-linux-android]' > .cargo/config.toml
        echo 'ar = "$HOME/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"' >> .cargo/config.toml
        echo 'linker = "$HOME/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"' >> .cargo/config.toml

    - name: Build for Android
      run: cargo ndk -t arm64-v8a build --features binary

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hackcomp-binary
        path: target/aarch64-linux-android/debug/hackcomp
